In [7]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


In [8]:
import tensorflow as tf
training_set = tf.keras.utils.image_dataset_from_directory(
   'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 10669 files belonging to 10 classes.


In [9]:
import tensorflow as tf
validation_set = tf.keras.utils.image_dataset_from_directory(
   'val',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 5342 files belonging to 10 classes.


In [13]:
training_set



<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 10), dtype=tf.float32, name=None))>

In [11]:
from tensorflow.keras.models import load_model


model = load_model("sequential_cnn_model.keras")

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 64, 64, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 64, 64, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 64, 64, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 32, 32, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 32, 32, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 16, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_10 (Conv2D)              │ (None, 16, 16, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_11 (Conv2D)              │ (None, 16, 16, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 8, 8, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 16384)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1024)           │    16,778,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │        10,250 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36,106,198 (137.73 MB)

 Trainable params: 18,053,098 (68.87 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 18,053,100 (68.87 MB)

In [15]:

for x,y in training_set:
    print(x,x.shape)
    print(x,y.shape)
    break


tf.Tensor(
[[[[140.75 134.75 160.75]
   [143.75 137.75 163.75]
   [139.5  133.5  159.5 ]
   ...
   [110.   105.   128.  ]
   [111.   106.   129.  ]
   [111.   106.   129.  ]]

  [[143.25 137.25 163.25]
   [140.25 134.25 160.25]
   [142.   136.   162.  ]
   ...
   [113.   108.   131.  ]
   [112.5  107.5  130.5 ]
   [116.5  111.5  134.5 ]]

  [[147.5  141.5  167.5 ]
   [148.5  142.5  168.5 ]
   [146.75 140.75 166.75]
   ...
   [113.   108.   131.  ]
   [110.25 105.25 128.25]
   [108.25 103.25 126.25]]

  ...

  [[115.   105.   129.  ]
   [112.   102.   126.  ]
   [113.25 103.25 127.25]
   ...
   [ 70.5   61.5   82.5 ]
   [ 77.5   68.5   89.5 ]
   [ 79.75  70.75  91.75]]

  [[111.5  101.5  125.5 ]
   [116.5  106.5  130.5 ]
   [109.25  99.25 123.25]
   ...
   [ 74.25  65.25  86.25]
   [ 73.5   64.5   85.5 ]
   [ 68.25  59.25  80.25]]

  [[111.25 101.25 125.25]
   [114.   104.   128.  ]
   [114.75 104.75 128.75]
   ...
   [ 76.75  67.75  88.75]
   [ 75.5   66.5   87.5 ]
   [ 72.75  63.75  8

In [28]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten
from tensorflow.keras.models import Sequential

In [29]:
model=Sequential()

In [30]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))
          

In [31]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))
          

In [32]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))
          

In [33]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))
          

In [34]:
model.add(Flatten())


In [35]:
model.add(Dense(units=1024,activation='relu'))

In [37]:
model.add(Dense(units=10,activation='softmax'))

In [38]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [40]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_4 (Conv2D)               │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 64, 64, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 32, 32, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 32, 32, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 16, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_10 (Conv2D)              │ (None, 16, 16, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_11 (Conv2D)              │ (None, 16, 16, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 8, 8, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 16384)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1024)           │    16,778,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │        10,250 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,960,746 (68.51 MB)

 Trainable params: 17,960,746 (68.51 MB)

 Non-trainable params: 0 (0.00 B)

In [41]:
training_history=model.fit(x=training_set,validation_data=validation_set,epochs=5)

Epoch 1/5
334/334 ━━━━━━━━━━━━━━━━━━━━ 351s 1s/step - accuracy: 0.2852 - loss: 2.9200 - val_accuracy: 0.6720 - val_loss: 0.9551
Epoch 2/5
334/334 ━━━━━━━━━━━━━━━━━━━━ 531s 2s/step - accuracy: 0.6819 - loss: 0.9516 - val_accuracy: 0.7849 - val_loss: 0.6344
Epoch 3/5
334/334 ━━━━━━━━━━━━━━━━━━━━ 708s 2s/step - accuracy: 0.7868 - loss: 0.6245 - val_accuracy: 0.8018 - val_loss: 0.5623
Epoch 4/5
334/334 ━━━━━━━━━━━━━━━━━━━━ 734s 2s/step - accuracy: 0.8347 - loss: 0.4689 - val_accuracy: 0.8222 - val_loss: 0.5024
Epoch 5/5
334/334 ━━━━━━━━━━━━━━━━━━━━ 807s 2s/step - accuracy: 0.8845 - loss: 0.3335 - val_accuracy: 0.8585 - val_loss: 0.3993


In [42]:
train_loss,train_acc =model.evaluate(training_set)

334/334 ━━━━━━━━━━━━━━━━━━━━ 168s 503ms/step - accuracy: 0.9192 - loss: 0.2401


In [43]:
print(train_loss,train_acc)

0.21735362708568573 0.9286718368530273


In [44]:
val_loss,vall_acc=model.evaluate(validation_set)

167/167 ━━━━━━━━━━━━━━━━━━━━ 65s 389ms/step - accuracy: 0.8572 - loss: 0.4068


In [46]:
print(val_loss,vall_acc)

0.3992926776409149 0.8584799766540527


In [47]:
model.save("againtrainedmodel.h5")

In [48]:
model.save("againtrainedmodel.keras")

In [49]:
import json
with open("training_hist.json","w")as f:
    json.dump(training_history.history,f)

In [ ]:
epochs=[i for i in range(1,11)]
plt.plot(epochs,training_history.history('train_accuracy'),color='red',label='Training_Accuracy')
plt.plot(epochs,training_history.history('val_accuracy'),color='blue',label='Validation_Accuracy')
plt.xlabel("No of Epochs")
plt.ylabel("Accuracy Result")
plt.title("Visualization of Accuracy Result")
plt.show()